// ═══════════════════════════════════════════════════════════════
//  AI ENGINE — 2 LAYER SYSTEM
//
//  LAYER 1 — SIGNAL ENGINE (smc.js — pure code, no AI)
//            Calculates: BOS, CHoCH, HH/HL/LL/LH, OB,
//            Liquidity, FVG, SL Hunt, EMA 5/10/20/30, Volume
//            Output: Raw Signal Object
//
//  LAYER 2 — CLAUDE DECISION MAKER
//            Reviews Layer 1 signal like a senior trader
//            Gives: TAKE / SKIP / WAIT verdict
//            Full breakdown: entry reason, risk warning,
//            best time to enter, confluence count
// ═══════════════════════════════════════════════════════════════

const axios = require("axios");

class AIEngine {

  // ══════════════════════════════════════════════════════════════
  //  LAYER 1 — SIGNAL SUMMARY BUILDER
  //  Pure code — no AI — summarizes SMC engine output
  // ══════════════════════════════════════════════════════════════
  static buildLayer1Signal(smcData) {
    const {
      currentPrice, overallBias, confidence,
      emaData, marketStructure, bos, choch,
      orderBlocks, liquidity, fvg, slHunts,
      volumeData, keyLevels,
      suggestedEntry, suggestedSL, suggestedTarget
    } = smcData;

    const ms = marketStructure || {};
    const msItems = (ms.structure || []);

    // Count confluences
    const confluences = [];
    if (bos.length > 0)         confluences.push(`BOS_${bos[0].type}`);
    if (choch.length > 0)       confluences.push(`CHoCH_${choch[0].type}`);
    if (msItems.some(s => s.type === "HH")) confluences.push("HH");
    if (msItems.some(s => s.type === "HL")) confluences.push("HL");
    if (msItems.some(s => s.type === "LL")) confluences.push("LL");
    if (msItems.some(s => s.type === "LH")) confluences.push("LH");
    if (orderBlocks.length > 0) confluences.push(`OB_${orderBlocks[orderBlocks.length-1].type}`);
    if (liquidity.length > 0)   confluences.push(`LIQ_SWEEP`);
    if (fvg.length > 0)         confluences.push(`FVG`);
    if (slHunts.length > 0)     confluences.push(`SL_HUNT`);
    if (emaData.trend.includes("BULLISH")) confluences.push("EMA_BULLISH");
    if (emaData.trend.includes("BEARISH")) confluences.push("EMA_BEARISH");
    if (volumeData.volumeSignal === "BULLISH_VOLUME") confluences.push("VOL_BULL");
    if (volumeData.volumeSignal === "BEARISH_VOLUME") confluences.push("VOL_BEAR");

    return {
      bias:           overallBias,
      engineScore:    confidence,
      confluences,
      confluenceCount: confluences.length,
      currentPrice,
      ema:            emaData,
      msTrend:        ms.trend || "UNDEFINED",
      msItems,
      bos,  choch,
      orderBlocks,
      liquidity,
      fvg,
      slHunts,
      volume:         volumeData,
      keyLevels,
      suggestedEntry,
      suggestedSL,
      suggestedTarget,
      // Quick flags
      hasBOS:    bos.length > 0,
      hasChoch:  choch.length > 0,
      hasOB:     orderBlocks.length > 0,
      hasLiq:    liquidity.length > 0,
      hasFVG:    fvg.length > 0,
      hasSLHunt: slHunts.length > 0,
      emaAligned: emaData.trend !== "SIDEWAYS",
      highVolume: volumeData.ratio > 1.5,
    };
  }

  // ══════════════════════════════════════════════════════════════
  //  LAYER 2 — CLAUDE DECISION MAKER PROMPT
  //  Claude acts as senior trader reviewing Layer 1 signal
  // ══════════════════════════════════════════════════════════════
  static buildLayer2Prompt(symbol, timeframe, layer1, extraContext = "") {
    const {
      bias, engineScore, confluences, confluenceCount,
      currentPrice, ema, msTrend, msItems,
      bos, choch, orderBlocks, liquidity, fvg, slHunts, volume,
      keyLevels, suggestedEntry, suggestedSL, suggestedTarget,
      hasBOS, hasChoch, hasOB, hasLiq, hasFVG, hasSLHunt,
      emaAligned, highVolume
    } = layer1;

    return `You are a SENIOR INSTITUTIONAL TRADER reviewing a signal generated by an automated SMC engine. Your job is DECISION MAKING — not signal generation.

The engine has already done the technical work. You must now decide:
1. Should I TAKE this trade?
2. Should I SKIP this trade?  
3. Should I WAIT for better confirmation?

═══ LAYER 1 ENGINE OUTPUT ═══
Symbol: ${symbol} | Timeframe: ${timeframe}
Engine Bias: ${bias} | Engine Score: ${engineScore}%
Current Price: ${currentPrice}

CONFLUENCE COUNT: ${confluenceCount} signals aligned
Active Confluences: ${confluences.join(", ") || "None"}

EMA STACK (5/10/20/30):
- EMA5=${ema.ema5} | EMA10=${ema.ema10} | EMA20=${ema.ema20} | EMA30=${ema.ema30}
- Trend: ${ema.trend} | Strength: ${ema.strength}%
- EMA Aligned: ${emaAligned ? "YES ✅" : "NO ❌"}
- Price near EMA20: ${ema.priceNearEma20 ? "YES ⚡" : "No"}
- Price near EMA30: ${ema.priceNearEma30 ? "YES ⚡" : "No"}

HTF MARKET STRUCTURE: ${msTrend}
${msItems.map(s => `- ${s.type}: ${s.description}`).join("\n") || "- No clear structure"}

MARKET STRUCTURE BREAKS:
- BOS: ${hasBOS ? bos.map(b => b.description).join(" | ") : "None"}
- CHoCH: ${hasChoch ? choch.map(c => c.description).join(" | ") : "None"}

ORDER BLOCKS:
${hasOB ? orderBlocks.map(o => `- ${o.type} [${o.strength}]: ${o.description}`).join("\n") : "- None detected"}

LIQUIDITY:
${hasLiq ? liquidity.map(l => `- ${l.description}`).join("\n") : "- No sweep detected"}

FAIR VALUE GAPS:
${hasFVG ? fvg.map(f => `- ${f.description}`).join("\n") : "- None"}

STOP LOSS HUNTS:
${hasSLHunt ? slHunts.map(s => `- ${s.description}`).join("\n") : "- None"}

VOLUME: ${volume.volumeSignal} | Ratio: ${volume.ratio}x avg | Climax: ${volume.isClimax ? "YES ⚠️" : "No"}
High Volume: ${highVolume ? "YES ✅" : "NO — weak move"}

KEY LEVELS:
- Resistance: ${keyLevels.immediateResistance}
- Support:    ${keyLevels.immediateSupport}

ENGINE SUGGESTED TRADE:
- Entry: ${suggestedEntry} | SL: ${suggestedSL} | Target: ${suggestedTarget}

${extraContext ? `TRADER NOTES: ${extraContext}` : ""}

═══ YOUR DECISION TASK ═══
As a senior trader, review this signal critically. Consider:
- Is confluence count strong enough? (3+ = good, 5+ = excellent)
- Does HTF structure support this trade?
- Is price at a valid SMC entry zone (OB, FVG, after liquidity sweep)?
- Is volume confirming the move?
- What are the key risks?
- Is this the RIGHT TIME to enter or should we wait?

Respond ONLY in this exact JSON (no markdown, no extra text):
{
  "verdict": "TAKE" or "SKIP" or "WAIT",
  "signal": "BUY" or "SELL" or "NEUTRAL",
  "confidence": <0-100>,

  "entryReason": "<2-3 sentences — exactly WHY this entry is valid by SMC rules, mention specific confluence>",
  "riskWarning": "<1-2 sentences — key risks, what could go wrong, market conditions to watch>",
  "bestTimeToEnter": "<specific condition — e.g. 'Wait for 1H candle close above OB at 2450', 'Enter on next 4H open', 'Wait for liquidity sweep at 2380 first'>",

  "entry": "<exact price level>",
  "stopLoss": "<exact price with reason>",
  "target1": "<first target — nearest resistance/support>",
  "target2": "<second target — extended move>",
  "rrRatio": "<e.g. 1:2.5>",

  "confluenceScore": <0-10>,
  "setupQuality": "A+" or "A" or "B" or "C" or "INVALID",

  "smcKey": "<single most important SMC reason for this trade>",
  "invalidation": "<exact price/condition that invalidates — e.g. 'Close below 2380 OB invalidates bullish setup'>",

  "verdictReason": "<1 sentence — why TAKE/SKIP/WAIT decision was made>"
}`;
  }

  // ── Claude API Call ──────────────────────────────────────────
  static async callClaude(prompt, apiKey) {
    const response = await axios.post(
      "https://api.anthropic.com/v1/messages",
      {
        model: "claude-sonnet-4-20250514",
        max_tokens: 1500,
        messages: [{ role: "user", content: prompt }]
      },
      {
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01"
        },
        timeout: 30000
      }
    );
    return response.data.content?.[0]?.text || "";
  }

  // ── Gemini Fallback ──────────────────────────────────────────
  static async callGemini(prompt, apiKey) {
    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
      {
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: { temperature: 0.2, maxOutputTokens: 1500 }
      },
      { timeout: 30000 }
    );
    return response.data.candidates?.[0]?.content?.parts?.[0]?.text || "";
  }

  // ── Parse Layer 2 Response ───────────────────────────────────
  static parseDecision(text, source, layer1) {
    try {
      const clean = text.replace(/```json|```/g, "").trim();
      const parsed = JSON.parse(clean);
      parsed.aiSource  = source;
      parsed.layer1    = layer1;  // attach layer1 data
      return parsed;
    } catch {
      // Fallback: use layer1 data to construct basic response
      return {
        verdict:         layer1.bias === "BULLISH" ? "WAIT" : layer1.bias === "BEARISH" ? "WAIT" : "SKIP",
        signal:          layer1.bias === "BULLISH" ? "BUY" : layer1.bias === "BEARISH" ? "SELL" : "NEUTRAL",
        confidence:      layer1.engineScore,
        entryReason:     "Engine detected " + layer1.confluences.join(", "),
        riskWarning:     "AI parse error — review manually",
        bestTimeToEnter: "Wait for confirmation",
        entry:           String(layer1.suggestedEntry),
        stopLoss:        String(layer1.suggestedSL),
        target1:         String(layer1.suggestedTarget),
        target2:         "—",
        rrRatio:         "—",
        confluenceScore: Math.min(10, layer1.confluenceCount),
        setupQuality:    layer1.confluenceCount >= 5 ? "A" : layer1.confluenceCount >= 3 ? "B" : "C",
        smcKey:          layer1.confluences[0] || "No strong confluence",
        invalidation:    "Price closes below support",
        verdictReason:   "Fallback — manual review needed",
        aiSource:        source,
        layer1
      };
    }
  }

  // ══════════════════════════════════════════════════════════════
  //  COST-OPTIMIZED FLOW:
  //
  //  Step 1: Layer 1 — Signal Engine (FREE — pure code)
  //  Step 2: Gemini  — Primary AI (FREE)
  //  Step 3: Claude  — Only if Gemini confidence >= 75% (PAID)
  //                    Claude does final validation on best setups
  //
  //  Result: 90%+ calls = Gemini (free)
  //          Only top setups = Claude (paid)
  // ══════════════════════════════════════════════════════════════

  // Threshold above which Claude validates Gemini's signal
  static CLAUDE_THRESHOLD = 75;

  static async analyze({ symbol, timeframe, smcData, claudeKey, geminiKey, extraContext }) {

    // ── LAYER 1: Pure code — no AI, no cost ──
    const layer1 = this.buildLayer1Signal(smcData);
    const prompt = this.buildLayer2Prompt(symbol, timeframe, layer1, extraContext);

    let geminiDecision = null;

    // ── STEP 2: Gemini PRIMARY (FREE) ──
    if (geminiKey) {
      try {
        console.log(`🟦 Gemini analyzing: ${symbol} ${timeframe}`);
        const text = await this.callGemini(prompt, geminiKey);
        geminiDecision = this.parseDecision(text, "Gemini", layer1);

        const geminiConf = geminiDecision.confidence || 0;
        const isHighConf = geminiConf >= this.CLAUDE_THRESHOLD;
        const isTake     = geminiDecision.verdict === "TAKE";

        console.log(`🟦 Gemini result: ${geminiDecision.verdict} | ${geminiConf}% | High conf: ${isHighConf}`);

        // ── STEP 3: Claude VALIDATOR — only if high confidence TAKE ──
        if (claudeKey && isHighConf && isTake) {
          try {
            console.log(`🟠 Claude validating high-confidence setup: ${symbol} ${geminiConf}%`);

            // Claude gets a shorter validation prompt — saves tokens
            const validationPrompt = this.buildClaudeValidationPrompt(
              symbol, timeframe, layer1, geminiDecision
            );

            const claudeText = await this.callClaude(validationPrompt, claudeKey);
            const claudeDecision = this.parseDecision(claudeText, "Claude+Gemini", layer1);

            // Merge: Claude's verdict is final, but keep Gemini's analysis
            return {
              ...claudeDecision,
              geminiSignal:     geminiDecision.signal,
              geminiVerdict:    geminiDecision.verdict,
              geminiConfidence: geminiConf,
              geminiReason:     geminiDecision.entryReason,
              claudeValidated:  true,
              aiSource:         "Claude ✅ (Gemini pre-screened)",
              layer1
            };

          } catch(e) {
            console.warn(`Claude validation failed: ${e.message} — using Gemini result`);
            geminiDecision.claudeValidated = false;
            geminiDecision.aiSource = "Gemini (Claude failed)";
            return geminiDecision;
          }
        }

        // Low confidence or SKIP/WAIT — return Gemini result directly (free)
        geminiDecision.claudeValidated = false;
        return geminiDecision;

      } catch(e) {
        console.warn(`Gemini failed: ${e.message} → Claude fallback`);
      }
    }

    // ── FALLBACK: Claude only (if no Gemini key) ──
    if (claudeKey) {
      try {
        console.log(`🟠 Claude only mode: ${symbol} ${timeframe}`);
        const text = await this.callClaude(prompt, claudeKey);
        const decision = this.parseDecision(text, "Claude", layer1);
        decision.claudeValidated = true;
        return decision;
      } catch(e) {
        throw new Error("Claude failed: " + e.message);
      }
    }

    throw new Error("No AI API key provided. Add GEMINI_API_KEY or CLAUDE_API_KEY.");
  }

  // ── Claude Validation Prompt (shorter = less tokens = less cost) ──
  static buildClaudeValidationPrompt(symbol, timeframe, layer1, geminiDecision) {
    return `You are validating a trading signal for ${symbol} (${timeframe}).

GEMINI AI already analyzed this and said:
- Verdict: ${geminiDecision.verdict}
- Signal: ${geminiDecision.signal}  
- Confidence: ${geminiDecision.confidence}%
- Entry: ${geminiDecision.entry} | SL: ${geminiDecision.stopLoss} | T1: ${geminiDecision.target1} | T2: ${geminiDecision.target2}
- Entry Reason: ${geminiDecision.entryReason}
- Risk Warning: ${geminiDecision.riskWarning}
- Setup Quality: ${geminiDecision.setupQuality}

SMC ENGINE DATA:
- Bias: ${layer1.bias} | Confluences (${layer1.confluenceCount}): ${layer1.confluences.join(", ")}
- HTF Trend: ${layer1.msTrend}
- EMA Trend: ${layer1.ema.trend}
- Has OB: ${layer1.hasOB} | Has Liquidity Sweep: ${layer1.hasLiq} | Has CHoCH: ${layer1.hasChoch}
- Volume: ${layer1.volume.volumeSignal} (${layer1.volume.ratio}x)
- Entry: ${layer1.suggestedEntry} | SL: ${layer1.suggestedSL} | Target: ${layer1.suggestedTarget}

Your job: CONFIRM or OVERRIDE Gemini's analysis.
- If you agree: keep verdict TAKE with your own levels
- If you disagree: change to SKIP or WAIT with reason

Respond ONLY in this exact JSON (no markdown):
{
  "verdict": "TAKE" or "SKIP" or "WAIT",
  "signal": "BUY" or "SELL" or "NEUTRAL",
  "confidence": <0-100>,
  "entryReason": "<2-3 sentences — your SMC validation>",
  "riskWarning": "<1-2 sentences — key risks>",
  "bestTimeToEnter": "<specific entry condition>",
  "entry": "<exact price>",
  "stopLoss": "<exact price>",
  "target1": "<price>",
  "target2": "<price>",
  "rrRatio": "<e.g. 1:2.5>",
  "confluenceScore": <0-10>,
  "setupQuality": "A+" or "A" or "B" or "C" or "INVALID",
  "smcKey": "<key SMC reason>",
  "invalidation": "<exact invalidation condition>",
  "verdictReason": "<1 sentence — why you agree/disagree with Gemini>"
}`;
  }
}

module.exports = AIEngine;
